### ISSUE TITLE
Hide files and settings that have no changes unless verbose on apply

### ISSUE THREAD

**Issue by jbellmore** [Chuckame/marlin-console-configurator#6]
This is a feature request to make the default output of `apply` operation to hide files and settings that will not be changed to show **only** the differences unless verbose output is requested.

This is needed particularly when dealing with Marlin 1.X due to the sheer number of files it lists. It is a huge list of "nothing to do" to sift through to see the actual changes.

Thanks again!

**Comment by Chuckame** [comment]
Like it, will do that! Will add `--display-non-changed` or something like that (or hope you have a better naming? 😁)

So by default: show only diff

And if param present: show all (diff & and not changed lines)

Edit: oh! Just read a second time the title, `--verbose` can be great!

**Comment by jbellmore** [comment]
Yeah I think --verbose (or -v for short, whichever) would be in line with most cli tools I have used in the past and should be pretty clear to most people I would think.

Thanks again!

**Comment by Chuckame** [comment]
@jbellmore is it what you want ? 😄 can you test it ?

**Comment by jbellmore** [comment]
> @jbellmore is it what you want ? 😄 can you test it ?

I'll try to give it a shot in the next couple days and let you know. Thanks!

**Comment by jbellmore** [comment]
Sorry for the long delay, finally getting a chance to test this out. Just built this branch, a corresponding docker image and ran it and it looks great! **So** much easier to read now, thank you!

Only comment I would make is I notice it still lists files with no changes (but shows  0 changes). This I assume is expected was a design decision and is expected behavior? I can see benefits to both leaving them in and taking them out and honestly I think either way is completely acceptable!

Thanks again!

**Comment by Chuckame** [comment]
Hey, no problem, thank you for the feedback!

Oh, sorry, this is just a little thing, I'll fix that and merge it to have it inside the official version.

**Comment by Chuckame** [comment]
@jbellmore can you test the new commit on https://github.com/Chuckame/marlin-console-configurator/pull/9 ? (I have no marlin files on this computer 😄 )

**Comment by Chuckame** [comment]
Done, usable with v1.3.0
